[package]
name = "kvs"
version = "0.1.0"
authors = ["邵靳天<sjt@hnu.edu.cn>"]
description = "A key-value store"
edition = "2018"

[dependencies]
clap = "2.32.0"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
clap = "2.32.0"
